### ISSUE TITLE
please upgrade the observation space

### ISSUE THREAD

**Issue by bionicles** [DoubleGremlin181/RubiksCubeGym#1]
is it possible for the observation space to be something about the state of the puzzle and not just a huge number? it's hard to understand the meaning of those numbers

**Comment by DoubleGremlin181** [comment]
The current observation space is a randomly assigned number for each state of the puzzle. You can look at `cube_reduced` and `cube` available through `info`.

The reason I chose not to use these as the observation space is because a lot of the combinations of their elements aren't valid states. For example, `YWWWOOGGRRBBOOGGRRBBWYYY` is not a valid 2x2x2 state even though it has four tiles of each color.

You can find the mapping of the tiles used in `cube` and `cube_reduced` in the [README](https://github.com/DoubleGremlin181/RubiksCubeGym/blob/master/README.md).

It isn't the best solution to the problem and I am open to suggestions about it
